### ISSUE TITLE
Bug with RWD

### ISSUE THREAD

**Issue by bohdansushchak** [przelewy24/p24-mobile-lib-android#2]
Express payment, once it show the mobile version but next it's desktop version of bank web page

<img width="242" alt="Screenshot 2021-02-17 at 09 47 34" src="https://user-images.githubusercontent.com/23574179/109614522-0a392d80-7b33-11eb-9e52-41f28879b877.png"> <img width="242" alt="Screenshot 2021-02-17 at 09 37 36" src="https://user-images.githubusercontent.com/23574179/109614527-0c02f100-7b33-11eb-84b1-9e5cd3e40a82.png">

**Comment by przelewy24mobile** [comment]
Unfortunately, the library has no affect on how the bank's website is displayed. I would suggest contacting your bank to report the problem
