### ISSUE TITLE
Activity being restarted after screen rotation

### ISSUE THREAD

**Issue by MateuszBogdan** [przelewy24/p24-mobile-lib-android#3]
According to documentation, adding
`android:configChanges="orientation|keyboard|keyboardHidden"`
would be sufficient to prevent reloading activity and restarting webview. For some reason it was not working properly on targetSdkVersion="30" (Android 11 - R) and emulator using Android 11 - API 30. View is reloaded after phone rotation.
To solve this issue I have added screenSize to the list resulting in
`android:configChanges="orientation|keyboard|keyboardHidden|screenSize"`
I am not entirely sure what is the root cause of this, I cannot find any reference in documentation about changes in this regard.

EDIT: I have revisited documentation and found out that there is probably an error in README.md. Text before code sample does not contain screenSize and in example code everything is in place.

**Comment by mareklat** [comment]
@MateuszBogdan Yes, that's right, we didn't document it. Thank you for reporting, fix has already been added.
