### ISSUE TITLE
Mobile library edge case handling

### ISSUE THREAD

**Issue by MateuszBogdan** [przelewy24/p24-mobile-lib-android#4]
I have transaction created from backend service which is handled on mobile device.
Happy path works ok, but when something goes wrong i am being redirected to UrlReturn page. On mobile I would expect Activity to end with an error and not to redirect to UrlReturn.

**Transaction timeouts (for testing purpose I have set TimeLimit to one minute):**
![image](https://user-images.githubusercontent.com/32546326/127291599-fdfd8eb8-a35a-4b50-9b4d-1941dd32f879.png)

This screen is being shown after transaction timeout which is ok, but clicking on **Powrót** button returns to UrlReturn page and Payment Activity is still active so mobile app is not informed about an error and in my case navigating to any page is pointless since payment is initiated by mobile app and i do not have dedicated "store" page.

Also there is some strange behavior when navigating around payment.
**Reproduction (tested at sandbox):**
1. Start payment
2. Pick payment method
3. Click back button

![image](https://user-images.githubusercontent.com/32546326/127292092-883034c1-f35c-476c-8a7d-1de2277916ab.png)

I presume internal error is caused by using sandbox environment (?)

**Comment by mareklat** [comment]
This looks like a problem on our backend side, not directly in the library. Probably the error page does not send a notification to the library. I would like to ask you to send your bug report at https://www.przelewy24.pl/pomoc/formularz-kontaktowy. Please indicate this issue so that technical support knows the context.
