### ISSUE TITLE
Problem z dołączeniem biblioteki

### ISSUE THREAD

**Issue by SoftSolid** [przelewy24/p24-mobile-lib-android#5]
Witam

Mam problem z dołączeniem do aplikacji biblioteki poprzez Maven

Could not find method p24() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

Proszę o pomoc.
Pozdrawiam
Robert

**Comment by mareklat** [comment]
@SoftSolid Czy w pliku build.gradle została dodana linijka `apply from: 'https://mobile.przelewy24.pl/p24lib.gradle'`? 
Proszę spojrzeć na tę sekcję dokumentacji:
https://github.com/przelewy24/p24-mobile-lib-android#adding-dependencies

**Comment by SoftSolid** [comment]
Tak. Została dodana

Tak wygląda plik.

// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: 'https://mobile.przelewy24.pl/p24lib.gradle'
buildscript {
    ext {
        RNNKotlinVersion = "1.3.61"
        RNNKotlinStdlib = "kotlin-stdlib-jdk8"
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
        p24()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.2.0'
        implementation "pl.przelewy24:p24lib:+"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by mareklat** [comment]
Proszę umieścić linijkę z adresem pluginu jak i implementację w konkretnym module, nie w pliku gradle roota projektu.
Można podejrzeć jak to jest rozwiązane w naszym przykładowym projekcie: https://github.com/przelewy24/p24-mobile-lib-android-example

**Comment by SoftSolid** [comment]
Witam

W android studio pokazuje mi coś takiego.
https://cs-cart.pl/2021-11-23_17-50-36.png

Proszę o sugestie.

**Comment by marcinkunert** [comment]
Naciśnij Sync Now na żółtej belce u góry.

wt., 23 lis 2021, 18:04 użytkownik Robert Diak ***@***.***>
napisał:

**Comment by SoftSolid** [comment]
Witam

Dziękuję to było to.

Pozdrawiam
Robert

**Comment by SoftSolid** [comment]
Panowie dopiero rozpoczynam przygodę z react native i proszę o wskazanie drogi. Mamy źródła aplikacji mobilnej i jest tam zaimplementowany paypal express. Na tej podstawie próbuję podłączyć p24.  Nie za bardzo wiem, jak przekazać sterowanie z aplikacji do modułu P24 wykonać płatność i wrócić do aplikacji. Można prosić o wskazanie jakiś artykułów lub informacji jak to zrobić?

Pozdrawiam
Robert

**Comment by mareklat** [comment]
@SoftSolid Mogę zasugerować zerknięcie nasz przykładowy, zarchiwizowany projekt integracji natywnych bibliotek z RN. Mam nadzieję, że okaże pomocny :)
https://github.com/przelewy24/p24-mobile-lib-react-native-example
