### ISSUE TITLE
Błędna formatka płatności, problem z notyfikacją

### ISSUE THREAD

**Issue by mateusz-dot** [przelewy24/p24-mobile-lib-android#6]
Witam,

mam dwa problemy z Państwa biblioteką.

1. Na formatce płatności nie wyświetlają się wszystkie zakładki - brakuje np "Karty", "Inne" - kanały te są uruchomione i np na stronie www wyświetlają się poprawnie. 
2. Notyfikacja wysyłana na urlStatus nie jest w postaci json'a tylko w postaci query parameters (czyli np p24_session_id=1111&p24_amount=1500...)

**Comment by mareklat** [comment]
@mateusz-dot 
Ad. 1. Prawdopodobnie konto nie zostało w pełni skonfigurowane pod bibliotekę mobilną. W przypadku SDK należy dodatkowo oznaczyć te kanały by były widoczne w wersji mobilnej. Sugeruję kontakt z naszym działem wsparcia (support@przelewy24.pl) i proszę wskazać w zgłoszeniu te issue.
Ad. 2. Ta kwestia też nie jest związana ściśle z biblioteką i również prosiłbym o kontakt z działem wsparcia. Sprawa zostanie skierowana do odpowiedniego działu.
