### ISSUE TITLE
Fixing a Zip Path Traversal Vulnerability 

### ISSUE THREAD

**Issue by tstepnik** [przelewy24/p24-mobile-lib-android#7]
Podczas próby wrzucenia apki do sklepu dostaje taki komunikat:

error
Przemierzanie ścieżki zip
Aplikacja zawiera niebezpieczny wzorzec rozpakowywania, który może oznaczać lukę w zabezpieczeniach dotyczącą przemierzania ścieżki. Zapoznaj się z tym artykułem w Centrum pomocy Google, by dowiedzieć się, jak rozwiązać ten problem.

Fixing a Zip Path Traversal Vulnerability - Google Help]( https://support.google.com/faqs/answer/9294009 )

pl.przelewy24.p24lib.a.b.a

**Comment by mareklat** [comment]
@tstepnik Którą wersje biblioteki używasz? Poprawka odnośnie tej podatności została dodana w wersji 3.5.29

**Comment by mareklat** [comment]
Closed due to no response
